version: '3.9'

services:
    php:
        container_name: gms-php
        image: namoshek/php-mssql:8.1-fpm
        ports:
            - "9000"
        volumes:
            - ./:/var/www/html #프로젝트 경로
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    apache:
        container_name: gms-apache
        build:
            context: './docker/apache/'
        depends_on:
            - php
        ports:
            - "7777:80"
        volumes:
            - ./:/var/www/html/
