version: '3.9'

services:
    php:
        container_name: ims-php
        build:
            context: './docker/php/'
        ports:
            - "9000"
        volumes:
            - ./:/var/www/html #프로젝트 경로
            #- ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    apache:
        container_name: ims-apache
        build:
            context: './docker/apache/'
        depends_on:
            - php
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html/
        environment:
            - CI_ENV=development
